name: Run Frontend Tests

on:
  push:
    branches:
      - master-fall24-g73
  pull_request:
    branches:
      - master-fall24-g73

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Replace with the Node.js version your frontend uses

      - name: Install Dependencies
        run: npm install

      - name: Run Tests and Save Output
        run: npm test > test-output.txt

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Create Gist with Test Results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth login --with-token <<< "$GITHUB_TOKEN"
          gh gist create test-output.txt --public --desc "Frontend Test Results"
